"""add language to posts

Revision ID: 943d06b14ce5
Revises: 24e6620cb109
Create Date: 2021-01-25 16:19:17.071817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943d06b14ce5'
down_revision = '24e6620cb109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
